In [1]:
#Libraries imported
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from array import array

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
df=pd.read_csv("Round2-DataScience-HomeworkData.csv")

Details about the dataset 

In [3]:
df.shape

(76995, 17)

In [4]:
df.dtypes

MEMBER_ID              object
LOB                    object
Voluntary              object
churned                 int64
Tenure                  int64
hadGap.                 int64
Age                     int64
SDOHScore             float64
conditionScore        float64
substanceScore        float64
physFrailtyScore      float64
mentalFrailtyScore    float64
EDCost                float64
EDCount               float64
IPCost                float64
IPCount               float64
State                  object
dtype: object

Getting summary of statistics for each features .

In [5]:
df.describe()

churned        Tenure  ...        IPCost       IPCount
count  76995.000000  76995.000000  ...  6.636500e+04  66365.000000
mean       0.327372   1429.131268  ...  4.700686e+03      0.524388
std        0.469257   1378.630014  ...  1.759468e+04      1.575237
min        0.000000      0.000000  ...  0.000000e+00      0.000000
25%        0.000000    335.000000  ...  0.000000e+00      0.000000
50%        0.000000    931.000000  ...  0.000000e+00      0.000000
75%        1.000000   2026.000000  ...  0.000000e+00      0.000000
max        1.000000   4552.000000  ...  1.381901e+06     80.000000

[8 rows x 13 columns]

*DATA CLEANING *

Handling Errors and Missing values

In [6]:
df.isnull()

MEMBER_ID    LOB  Voluntary  churned  ...  EDCount  IPCost  IPCount  State
0          False  False       True    False  ...    False   False    False  False
1          False  False       True    False  ...    False   False    False  False
2          False  False       True    False  ...    False   False    False  False
3          False  False       True    False  ...    False   False    False  False
4          False  False       True    False  ...    False   False    False  False
...          ...    ...        ...      ...  ...      ...     ...      ...    ...
76990      False  False       True    False  ...    False   False    False  False
76991      False  False      False    False  ...     True    True     True  False
76992      False  False       True    False  ...    False   False    False  False
76993      False  False      False    False  ...    False   False    False  False
76994      False  False       True    False  ...    False   False    False  False

[76995 rows x 17 columns]

In [7]:
df.isnull().sum()

MEMBER_ID                 0
LOB                       0
Voluntary             51789
churned                   0
Tenure                    0
hadGap.                   0
Age                       0
SDOHScore                 0
conditionScore            0
substanceScore            0
physFrailtyScore          0
mentalFrailtyScore        0
EDCost                10630
EDCount               10630
IPCost                10630
IPCount               10630
State                     0
dtype: int64

In [8]:
df['EDCost'].unique()

array([   0.  ,     nan,  566.09, ..., 2260.36, 1326.07,  505.13])

In [9]:
df['IPCost'].unique()

array([    0.  ,      nan, 13264.66, ..., 11217.79,  4092.36,  7749.26])

In [10]:
df['IPCount'].unique()

array([ 0., nan,  1.,  2.,  3.,  5.,  6.,  4.,  7., 18., 10., 13.,  8.,
        9., 15., 12., 11., 14., 17., 23., 21., 20., 51., 16., 36., 19.,
       47., 80., 22., 27., 24., 25., 37.])

In [11]:
df['EDCount'].unique()

array([  0.,  nan,   2.,   1.,   3.,   4.,   9.,   5.,   7.,  16.,   6.,
        10.,  35.,  11.,  13.,   8.,  26.,  20.,  15.,  29.,  18.,  12.,
        21.,  17.,  33.,  97.,  14.,  22.,  45.,  36.,  49.,  30., 102.,
        31.,  70.,  24.,  34.,  25.,  23.,  19.,  52.,  77.,  55.,  47.,
        28.,  42.,  53.,  32.,  38.,  62.,  46., 146.,  37.,  43.,  67.,
        44.,  59.,  68.,  95., 179.,  27.,  65.,  51.,  40.,  50.,  39.,
        83.,  48.,  58., 126.,  41., 230., 127.,  80., 287.,  63.,  88.,
       107.,  60., 100.,  54., 122.,  56.,  79.,  89.])

In [12]:
df["Voluntary"]

0                                   NaN
1                                   NaN
2                                   NaN
3                                   NaN
4                                   NaN
                      ...              
76990                               NaN
76991    Involuntary - Medicare / Other
76992                               NaN
76993                         Voluntary
76994                               NaN
Name: Voluntary, Length: 76995, dtype: object

In [13]:
pd.unique(df[['Voluntary','churned']].values.ravel())

array([nan, 0, 'Voluntary', 1, 'Involuntary - Medicare / Other',
       'Involuntary - SNP'], dtype=object)

To know that there are no churned value for nan in Voluntary Column 

In [14]:
group = df.groupby('Voluntary')
df2 = group.apply(lambda x: x['churned'].unique())
df2

Voluntary
Involuntary - Medicare / Other    [1]
Involuntary - SNP                 [1]
Voluntary                         [1]
dtype: object

In [15]:
df[['Voluntary']] = df[['Voluntary']].fillna(value='NA')

In [16]:
df

MEMBER_ID   LOB  ... IPCount  State
0      7ea90bb64201ddaf463eb9419ad990d9  LOB2  ...     0.0     PA
1      6319ce06253302493c1fe5d57d57aba7  LOB1  ...     0.0     PA
2      e7c98ad14a283b1bb751dd73b76f1ef9  LOB1  ...     0.0     PA
3      6189fb5bf21454cb7c01f15cb1bb78ec  LOB4  ...     0.0     NC
4      8793004f217e16c695b043fa78b9c74b  LOB5  ...     0.0     OH
...                                 ...   ...  ...     ...    ...
76990  961d9e7363a1e93ef1876c84902a8814  LOB1  ...     0.0     PA
76991  6c758a8b40551f58859ae4a13753ff35  LOB1  ...     NaN     PA
76992  4c293edf31e79b408e231651a3b1448f  LOB1  ...     0.0     PA
76993  87b2ee8c4461df5ac5f75efab9b09916  LOB2  ...     1.0     PA
76994  e125a0255398f478c3d5e2e5ab09d0b8  LOB1  ...     0.0     PA

[76995 rows x 17 columns]

In [17]:
df=df.drop(['Voluntary'], axis=1)

In [18]:
df[['EDCost','IPCost','IPCount','EDCount']] = df[['EDCost','IPCost','IPCount','EDCount']].fillna(value=0)

In [19]:
df.isnull().sum()

MEMBER_ID             0
LOB                   0
churned               0
Tenure                0
hadGap.               0
Age                   0
SDOHScore             0
conditionScore        0
substanceScore        0
physFrailtyScore      0
mentalFrailtyScore    0
EDCost                0
EDCount               0
IPCost                0
IPCount               0
State                 0
dtype: int64

**DATA TRANSFORMATION**

In [20]:
df.dtypes

MEMBER_ID              object
LOB                    object
churned                 int64
Tenure                  int64
hadGap.                 int64
Age                     int64
SDOHScore             float64
conditionScore        float64
substanceScore        float64
physFrailtyScore      float64
mentalFrailtyScore    float64
EDCost                float64
EDCount               float64
IPCost                float64
IPCount               float64
State                  object
dtype: object

In [21]:
df.head(5)

MEMBER_ID   LOB  churned  ...  IPCost  IPCount  State
0  7ea90bb64201ddaf463eb9419ad990d9  LOB2        0  ...     0.0      0.0     PA
1  6319ce06253302493c1fe5d57d57aba7  LOB1        0  ...     0.0      0.0     PA
2  e7c98ad14a283b1bb751dd73b76f1ef9  LOB1        0  ...     0.0      0.0     PA
3  6189fb5bf21454cb7c01f15cb1bb78ec  LOB4        0  ...     0.0      0.0     NC
4  8793004f217e16c695b043fa78b9c74b  LOB5        0  ...     0.0      0.0     OH

[5 rows x 16 columns]

Visualization :
Count of Churns in each state

In [22]:
states= df[df['churned']>0]

In [23]:
states

MEMBER_ID   LOB  churned  ...    IPCost  IPCount  State
6      225c2be6cbe078fe20d12ea66b375bf8  LOB1        1  ...      0.00      0.0     PA
14     19463dcc2d19329ca148879baf9416d3  LOB5        1  ...      0.00      0.0     OH
21     f1f8cdb47a28ab33c51cfbf506e97ffc  LOB4        1  ...      0.00      0.0     NC
62     e76c6488074d133c5878dccb780c2969  LOB1        1  ...      0.00      0.0     PA
87     07746dc6951a76f405392db15c9fa92d  LOB4        1  ...      0.00      0.0     NC
...                                 ...   ...      ...  ...       ...      ...    ...
76979  51db0d65cf282e09bc2b7e204f241857  LOB1        1  ...      0.00      0.0     PA
76982  7d6655de83fba98f5a2536831538af6a  LOB1        1  ...  11217.79      1.0     PA
76986  3b510464105122b132fe0c9920473bbc  LOB1        1  ...   4092.36      1.0     PA
76991  6c758a8b40551f58859ae4a13753ff35  LOB1        1  ...      0.00      0.0     PA
76993  87b2ee8c4461df5ac5f75efab9b09916  LOB2        1  ...   7749.26      1.0     PA

[25206 rows x 16 columns]

In [24]:
visualization = df[['churned','State']]
visualization

churned State
0            0    PA
1            0    PA
2            0    PA
3            0    NC
4            0    OH
...        ...   ...
76990        0    PA
76991        1    PA
76992        0    PA
76993        1    PA
76994        0    PA

[76995 rows x 2 columns]

In [25]:
st=visualization.groupby('State').count()[['churned']]
st.columns

Index(['churned'], dtype='object')

**Encoding categorical variables **

In [26]:
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing 

In [27]:
# creating instance of labelencoder
labelencoder = LabelEncoder()

In [28]:
label_encoder = preprocessing.LabelEncoder()
df['LOB']= label_encoder.fit_transform(df['LOB']) 
df['State']= label_encoder.fit_transform(df['State']) 
df

MEMBER_ID  LOB  churned  ...   IPCost  IPCount  State
0      7ea90bb64201ddaf463eb9419ad990d9    1        0  ...     0.00      0.0      3
1      6319ce06253302493c1fe5d57d57aba7    0        0  ...     0.00      0.0      3
2      e7c98ad14a283b1bb751dd73b76f1ef9    0        0  ...     0.00      0.0      3
3      6189fb5bf21454cb7c01f15cb1bb78ec    3        0  ...     0.00      0.0      1
4      8793004f217e16c695b043fa78b9c74b    4        0  ...     0.00      0.0      2
...                                 ...  ...      ...  ...      ...      ...    ...
76990  961d9e7363a1e93ef1876c84902a8814    0        0  ...     0.00      0.0      3
76991  6c758a8b40551f58859ae4a13753ff35    0        1  ...     0.00      0.0      3
76992  4c293edf31e79b408e231651a3b1448f    0        0  ...     0.00      0.0      3
76993  87b2ee8c4461df5ac5f75efab9b09916    1        1  ...  7749.26      1.0      3
76994  e125a0255398f478c3d5e2e5ab09d0b8    0        0  ...     0.00      0.0      3

[76995 rows x 16 columns]

In [29]:
df=df.drop(['MEMBER_ID'], axis=1)

In [30]:
df

LOB  churned  Tenure  hadGap.  ...  EDCount   IPCost  IPCount  State
0        1        0      49        0  ...      0.0     0.00      0.0      3
1        0        0      49        0  ...      0.0     0.00      0.0      3
2        0        0      49        0  ...      0.0     0.00      0.0      3
3        3        0      49        0  ...      0.0     0.00      0.0      1
4        4        0      49        0  ...      0.0     0.00      0.0      2
...    ...      ...     ...      ...  ...      ...      ...      ...    ...
76990    0        0    4552        0  ...      0.0     0.00      0.0      3
76991    0        1      21        0  ...      0.0     0.00      0.0      3
76992    0        0    2087        1  ...      1.0     0.00      0.0      3
76993    1        1      91        0  ...      1.0  7749.26      1.0      3
76994    0        0    4552        0  ...      2.0     0.00      0.0      3

[76995 rows x 15 columns]

**Visualization for analysis**

Calculating the count of churns in each and every state

**Risk score prediction**

In [32]:
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestRegressor


In [33]:

y = df['churned']
X=df.drop(['churned'], axis=1)

In [34]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [35]:
log_regression=LogisticRegression(multi_class="auto",solver="lbfgs",C=1.0,max_iter=100,random_state=42)
log_regression.fit(X_train,y_train)
pred_log=log_regression.predict(X_test)
acc_score=accuracy_score(y_test,pred_log)
print(acc_score)

0.7293478688653626


In [36]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(log_regression, X_train, y_train, cv=10)
print('Cross-Validation Accuracy Scores', scores)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Cross-Validation Accuracy Scores [0.71040899 0.73289397 0.72901725 0.72126381 0.71467339 0.71893778
 0.72004653 0.72586274 0.73090345 0.71985266]


In [37]:
nn_classifier=MLPClassifier(hidden_layer_sizes=(50,2),max_iter=100,verbose=True,solver='adam',n_iter_no_change=10,activation='identity')
nn_classifier.fit(X_train,y_train)
pred_random=nn_classifier.predict(X_test)
acc_score=accuracy_score(y_test,pred_random)
print(acc_score)

Iteration 1, loss = inf
Iteration 2, loss = inf
Iteration 3, loss = inf
Iteration 4, loss = inf
Iteration 5, loss = inf
Iteration 6, loss = inf
Iteration 7, loss = inf
Iteration 8, loss = inf
Iteration 9, loss = inf
Iteration 10, loss = inf
Iteration 11, loss = inf
Iteration 12, loss = inf
Iteration 13, loss = inf
Iteration 14, loss = inf
Iteration 15, loss = inf
Iteration 16, loss = inf
Iteration 17, loss = inf
Iteration 18, loss = inf
Iteration 19, loss = inf
Iteration 20, loss = inf
Iteration 21, loss = inf
Iteration 22, loss = inf
Iteration 23, loss = inf
Iteration 24, loss = inf
Iteration 25, loss = inf
Iteration 26, loss = inf
Iteration 27, loss = inf
Iteration 28, loss = inf
Iteration 29, loss = inf
Iteration 30, loss = 0.56860165
Iteration 31, loss = inf
Iteration 32, loss = 0.56882071
Iteration 33, loss = 0.56317938
Iteration 34, loss = 0.56306378
Iteration 35, loss = 0.57085460
Iteration 36, loss = 0.56570935
Iteration 37, loss = 0.56230596
Iteration 38, loss = 0.56109730
Ite